version: "3"

networks:
  default:
    driver: bridge
  traefik:
    external: true
    name: traefik

services:
  traefik:
    image: traefik
    networks:
      - default
      - traefik
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

