# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: down
      - task: trado
      - task: up
      - task: log
  trado:
    cmds:
      - trado || echo "done"
  down:
    cmds:
      - docker compose down
  up:
    cmds:
      - docker compose up -d
  log:
    cmds:
      - docker compose logs -f
