[log]
  level = "DEBUG"

[providers.docker]
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"
  network = "traefik"

[api]
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
  [entryPoints.dashboard]
    address = ":8080"

[certificatesResolvers]
  [certificatesResolvers.default.acme]
    email = bobuk@rubedo.cloud
    storage = "/letsencrypt/acme.json"
    [certificatesResolvers.default.acme.tlsChallenge]

